

export const products = [
    {
        "caOption": "1",
        "optionStatus": ["ENABLED", "DISABLED"],
        "tech": "",
        "type": ["CASH"],
        "ccy": "EUR",
        "ratio": 1,
        "percentage": 0,
        "benefitSecurity": 0,
        "dbcr": ["CREDIT"],
        "ecsroAccount": "",
        "label": ""
    },
    {
        "caOption": "1",
        "optionStatus": ["ENABLED", "DISABLED"],
        "tech": "",
        "type": ["CASH"],
        "ccy": "EUR",
        "ratio": 100,
        "percentage": 100,
        "benefitSecurity": "GBSRD0288449",
        "dbcr": ["CREDIT"],
        "ecsroAccount": "",
        "label": ""
    },
    {
        "caOption": "",
        "optionStatus": [],
        "tech": "",
        "type": [],
        "ccy": "",
        "ratio": "",
        "percentage": "",
        "benefitSecurity": "",
        "dbcr": [],
        "ecsroAccount": "",
        "label": ""
    },
    {
        "caOption": "",
        "optionStatus": [],
        "tech": "",
        "type": [],
        "ccy": "",
        "ratio": "",
        "percentage": "",
        "benefitSecurity": "",
        "dbcr": [],
        "ecsroAccount": "",
        "label": ""
    },
    {
        "caOption": "",
        "optionStatus": [],
        "tech": "",
        "type": [],
        "ccy": "",
        "ratio": "",
        "percentage": "",
        "benefitSecurity": "",
        "dbcr": [],
        "ecsroAccount": "",
        "label": ""
    },
    {
        "caOption": "",
        "optionStatus": [],
        "tech": "",
        "type": [],
        "ccy": "",
        "ratio": "",
        "percentage": "",
        "benefitSecurity": "",
        "dbcr": [],
        "ecsroAccount": "",
        "label": ""
    },
    {
        "caOption": "",
        "optionStatus": [],
        "tech": "",
        "type": [],
        "ccy": "",
        "ratio": "",
        "percentage": "",
        "benefitSecurity": "",
        "dbcr": [],
        "ecsroAccount": "",
        "label": ""
    },
    {
        "caOption": "",
        "optionStatus": [],
        "tech": "",
        "type": [],
        "ccy": "",
        "ratio": "",
        "percentage": "",
        "benefitSecurity": "",
        "dbcr": [],
        "ecsroAccount": "",
        "label": ""
    },
    {
        "caOption": "",
        "optionStatus": [],
        "tech": "",
        "type": [],
        "ccy": "",
        "ratio": "",
        "percentage": "",
        "benefitSecurity": "",
        "dbcr": [],
        "ecsroAccount": "",
        "label": ""
    },
    {
        "caOption": "",
        "optionStatus": [],
        "tech": "",
        "type": [],
        "ccy": "",
        "ratio": "",
        "percentage": "",
        "benefitSecurity": "",
        "dbcr": [],
        "ecsroAccount": "",
        "label": ""
    },
    {
        "caOption": "",
        "optionStatus": [],
        "tech": "",
        "type": [],
        "ccy": "",
        "ratio": "",
        "percentage": "",
        "benefitSecurity": "",
        "dbcr": [],
        "ecsroAccount": "",
        "label": ""
    },
    {
        "caOption": "",
        "optionStatus": [],
        "tech": "",
        "type": [],
        "ccy": "",
        "ratio": "",
        "percentage": "",
        "benefitSecurity": "",
        "dbcr": [],
        "ecsroAccount": "",
        "label": ""
    },
    {
        "caOption": "",
        "optionStatus": [],
        "tech": "",
        "type": [],
        "ccy": "",
        "ratio": "",
        "percentage": "",
        "benefitSecurity": "",
        "dbcr": [],
        "ecsroAccount": "",
        "label": ""
    },
];